modLoader="javafml"
loaderVersion="[${loaderversion},)"
license="MIT License https://github.com/McJtyMods/DeepResonance/blob/1.16/LICENCE"
issueTrackerURL="https://github.com/McJtyMods/DeepResonance/issues"
displayURL="https://github.com/McJtyMods/DeepResonance"
authors="Elec332, McJty"

[[mods]]
modId="deepresonance"
version="${version}"
displayName="DeepResonance"
description="Power generation based on resonating crystals."

[[dependencies.deepresonance]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepresonance]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[${libversion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.deepresonance]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepresonance]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[${baseversion},)"
    ordering="AFTER"
    side="BOTH"
