modLoader="javafml"
loaderVersion="[39,)"
license="MIT License https://github.com/McJtyMods/DeepResonance/blob/1.18/LICENCE"
issueTrackerURL="https://github.com/McJtyMods/DeepResonance/issues"
displayURL="https://github.com/McJtyMods/DeepResonance"
authors="Elec332, McJty"

[[mods]]
modId="deepresonance"
version="${file.jarVersion}"
displayName="DeepResonance"
description="Power generation based on resonating crystals."

[[dependencies.deepresonance]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepresonance]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.18-6.0.15,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.deepresonance]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.18-3.0.8,)"
    ordering="AFTER"
    side="BOTH"